version: "3.7"
services:
  restic:
    build: .
    ## Configuation
    environment:
      ## In this example Backblaze B2 is used
      ## NB: repository should be initiazed before use
      ## IE: restic -r b2:bucketname:path/to/repo init
      ## Check Please check: https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html
      - RESTIC_REPOSITORY=b2:bucketname:path/to/repo
      - RESTIC_PASSWORD=test
      ## Cron rule (0 0 * * * - Once a day at midnight)
      - BACKUP_CRON=* * * * *
      ## How many backups to store
      - RESTIC_FORGET_ARGS=--keep-last 10
      - RESTIC_JOB_ARGS
      ## Backend specific settings. Please check: https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html
      ## Example for Backblaze B2
      - B2_ACCOUNT_ID=<MY_ACCOUNT_ID>
      - B2_ACCOUNT_KEY=<MY_SECRET_ACCOUNT_KEY>
    volumes:
      # Persistent storage of restic cache (greatly speeds up all restic operations)
      - restic_cache:/root/.cache/restic
      ## Mount all your data to backup inside /data in container
      ## /opt directory
      # - /opt:/data/opt
      ## All docker volumes
      # - /var/lib/docker/volumes:/data/volumes
    restart: always

volumes:
  restic_cache:
