version: "3.7"
services:
  restic:
    build: .
    env_file:
      - .env
    volumes:
      # Persistent storage of restic cache (greatly speeds up all restic operations)
      - restic_cache:/root/.cache/restic
      ## Mount all your data to backup inside /data in container
      ## /opt directory
      # - /opt:/data/opt
      ## All docker volumes
      # - /var/lib/docker/volumes:/data/volumes
      - ./:/data
    restart: always

volumes:
  restic_cache:
